#! /bin/bash -e

clear

export fsbench_utils_dir=$PWD/fsbench-utils

. config || {
    cat << EOF
There's no config file in the current directory.
Please create it (see config.sample).

EOF
    exit 1
}

mkdir -p `dirname ${logfile}`
echo -e "##########$(date)##########\n" > $logfile


cleanup()
{
    umount "${mount_dir}" &> /dev/null
}

get_result_name()
{
    result=`readlink -m "${result_dir}/${fs_name}/${iosched_name}-${benchmark_name}"`
	export result
}

run_single()
{
    trap cleanup EXIT

    get_result_name

    [ -f "${result}" ] && return

    "${fs}" prepare
    "${iosched}" prepare
    mkdir -p `dirname "${result}"`
    echo 3 > /proc/sys/vm/drop_caches
    "${benchmark}" run
    "${fs}" cleanup
}

run()
{
	for fs in fs/*/* ; do
        [ -x "${fs}" ] || continue
		fs_name=`basename ${fs}`

        for iosched in iosched/* ; do
            [ -x "${iosched}" ] && "${iosched}" use || continue
			iosched_name=`basename ${iosched}`

            for benchmark in benchmark/* ; do
                [ -x "${benchmark}" ] && "${benchmark}" use || continue
				benchmark_name=`basename ${benchmark}`
				echo -e "\n${fs_name}/${iosched_name}/${benchmark_name}"

                run_single
            done
        done
    done
}

print_help()
{
    cat << EOF
Usage: run [help]

	run:		run benchmarks
	show:		show the results of benchmarks
	run help:	this help
EOF
}

case "$1" in
    "")
        run
        ;;

    run_single)
        run_single
        ;;

	show)
		python fsbench-utils/show_benchmarks.py config
		;;
    *)
        print_help
        ;;

esac
