#! /bin/bash -e

export PATH=$PATH:$PWD/fsbench-utils

. config || {
    cat << EOF
There's no config file in the current directory.
Please create it (see config.sample).

EOF
    exit 1
}

cleanup()
{
    umount "${mount_dir}"
}

get_result_name()
{
    fs_name=`basename $(dirname "${fs}")`
	iosched_name=`basename "${iosched}"`
	benchmark_name=`basename "${benchmark}"`
    result=`readlink -m "${result_dir}/${fs_name}/${iosched_name}-${benchmark_name}"`
	export result
}

run_single()
{
    trap cleanup EXIT

    get_result_name

    [ -f "${result}" ] && return

    "${fs}" prepare
    "${iosched}" prepare
    mkdir -p `dirname "${result}"`
    echo 3 > /proc/sys/vm/drop_caches
    "${benchmark}" run
    "${fs}" cleanup
}

run()
{
    for fs in fs/*/* ; do
        [ -x "${fs}" ] || continue
        echo ${fs}

        for iosched in iosched/* ; do
            [ -x "${iosched}" ] && "${iosched}" use || continue
            echo ${iosched}

            for benchmark in benchmark/* ; do
                [ -x "${benchmark}" ] && "${benchmark}" use || continue
                echo ${benchmark}

                run_single
            done
        done
    done
}

print_help()
{
    cat << EOF
Usage: run [help]

        run:            run benchmarks
        run help:       this help
EOF
}

case "$1" in
    "")
        run
        ;;

    run_single)
        run_single
        ;;

    *)
        print_help
        ;;

esac
