#! /bin/bash

cd `dirname "$0"`
. common

case "$1" in
    prepare)
        devname=`basename "${device}"`
        while ! [ -d /sys/block/${devname} ] ; do
            devname=${devname:0:-1}
        done
		scheduler=`basename "$0"`
		trap 'error_exit $0' ERR
        action "Set $scheduler I/O Scheduler:" change_ioscheduler $scheduler /sys/block/${devname}/queue/scheduler
        ;;

    use)
        use
        ;;
esac
